### ISSUE TITLE
Having trouble running this example

### ISSUE THREAD

**Issue by karthickg8** [SanichKotikov/react-family-tree-example#1]
This is more a question than a issue for this software/branch.
I have been trying to use 'react-family-tree' module without much success.

I installed react (following this tutorial -> https://www.youtube.com/watch?v=Ke90Tje7VS0&t=2500s)
I wanted to use your library in my react application.
The example program differs a lot from the application I created (using create-react-app my-family-tree). Though I managed to install the required modules (react-family-tree, relatives-tree,..).

It would be very useful and easy either if I can just download and run this 'react-family-tree-example' or at least please explain steps to be followed to run this sample program.

I tried to run .\react-family-tree-example-master\public\index.html, page is blank.

Hope to get it working in my machine :).

Cheers,
Karthick

**Comment by SanichKotikov** [comment]
@karthickg8 just download whole project and run it as any other CRA (create-react-app) project: `npm i && npm start`.

Please note that React is just a rendering layer in this example. The core library is https://github.com/SanichKotikov/relatives-tree and you can use it with any rendering libs/framework, or with even native JS.

**Comment by karthickg8** [comment]
Indeed, it worked :).

Thanks!
