### ISSUE TITLE
 how to do expand and collapse

### ISSUE THREAD

**Issue by zack-dot** [SanichKotikov/react-family-tree-example#10]

**Comment by SanichKotikov** [comment]
Please, provide more information. I have no idea what do u asking...

**Comment by zack-dot** [comment]
When I click on the particular node from the tree view, the selected node-related relationship should be collapsed. When I click on the same node again it has to be expanded with a related relationship. How we can do it?

**Comment by SanichKotikov** [comment]
There are no plans to add such functionality in the near future.
